name: JMeter

on:
  workflow_dispatch:  # Permite ejecutarlo manualmente desde Actions

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y jmeter

      - name: Run JMeter test
        run: |
          mkdir -p results
          jmeter -n -t TestPlans/jsonplaceholder_prueba.jmx -l results/result.jtl -e -o results/report

      - name: Upload raw results (.jtl)
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results/result.jtl

      - name: Upload HTML dashboard
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-report
          path: results/report
